services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./squirrel/:/var/www/html
    ports:
      - "8080:80"
    restart: unless-stopped

  php:
    build:
      context: ./php
      dockerfile: Dockerfile
    container_name: php
    volumes:
      - ./squirrel/:/var/www/html
    working_dir: /var/www/html

  postfix:
    build:
      context: ./postfix
      dockerfile: Dockerfile
    container_name: postfix

  dovecot:
    build:
      context: ./dovecot
      dockerfile: Dockerfile
    container_name: dovecot
    depends_on:
      - postfix
